export default defineAppConfig({
  pages: [
        'pages/index/index',
        'pages/characterPage/index',
        'pages/backgroundInfo/index',
        'pages/menu/index',
        'pages/chapterSelect/index',
        'pages/chapterSelect2/index',
        'pages/chapterSelect3/index',
        'pages/chapterSelect4/index',
        'pages/allstudents/index',
        'pages/gameChapters/chapter0/Chapter0packed',
        'pages/gameChapters/chapter1/Chapter1packed',
        'pages/gameChapters/chapter2/Chapter2packed',
        'pages/gameChapters/chapter3/Chapter3packed',
        'pages/gameChapters/chapter4/Chapter4packed',
        'pages/gameChapters/chapter5/Chapter5packed',
        'pages/gameChapters/chapter6/Chapter6packed',
        'pages/gameChapters/chapter7/Chapter7packed',
        'pages/gameChapters/chapter8/Chapter8packed',
        'pages/gameChapters/chapter9/Chapter9packed',
        'pages/gameChapters/chapter10/Chapter10packed',
        'pages/gameChapters/chapter11/Chapter11packed',
        'pages/gameChapters/chapter12/Chapter12packed',
        'pages/gameChapters/chapter13/Chapter13packed',
        'pages/gameChapters/chapter14/Chapter14packed',
        'pages/gamepage/gamechoose/index',
        'pages/gamepage/hammergame/index',
        'pages/gamepage/bublegame/index',
        'pages/knowlegePage/index',
            'pages/examplePage/index'
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: '',
    navigationBarTextStyle: 'black',
    navigationStyle:"custom",
    pageOrientation:'landscape'
  }
})
